
[package]
name = "atpage"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
lto = true
strip = true 

#[dev-dependencies]
#console_error_panic_hook = { workspace = true }

[dependencies]
leptos = { version = "0.8.20", features = ["csr"] }
leptos_meta = "0.8.6"
leptos_router = "0.8.15"
leptos-use = "0.19.0"
phosphor-leptos = "0.8.0"

itertools = "0.15.0"
chrono = "0.4.45"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
futures = "0.3.33"
reqwest = { version = "0.13.4", features = ["json"] }
codee = { version = "0.3.5", features = ["prost", "json_serde"] }

slug = "0.1.6"
latex2mathml = "0.2.3"

web-sys = { version = "0.3.83", features = ["Document", "HtmlElement"] } 

[dependencies.pulldown-cmark]
version = "0.13.4"
default-features = false 
features = ["simd", "html"]

[dependencies.gloo]
version = "0.11.0"
features = ["futures"]
