[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx @tailwindcss/cli -i input.css -o asset/main.css"]

[build]
release = true
dist = "dist"
public_url = "/"
filehash = true 
minify = "always" 

[watch]
watch = []
ignore = ["./asset", "./shared", "./devlog.md", "./README.md"]

[serve]
address = "127.0.0.1"
port = 3001
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false

[tools]
wasm_bindgen = "0.2.114"
wasm_opt = "version_123"
tailwindcss = "4.1.15"
